---

- block:
  - name: Add multiple repositories into the same file (1/2) (Centos)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no

  - name: Add multiple repositories into the same file (2/2) (Centos)
    yum_repository:
      name: rpmforge
      description: RPMforge YUM repo
      file: external_repos
      baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
      mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
      enabled: no

  - name: update the system (Centos)
    raw: sudo yum update
    register: centosupdate_result
    changed_when: False
    until: centosupdate_result is success
    retries: 5
    ignore_errors: yes

  - name: Install Packages (Centos)
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ initial_packages_centos }}"
    ignore_errors: yes

  - name: Disallow root SSH access (Centos)
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\s'
      line: 'PermitRootLogin no'
      state: present
    notify: Restart sshd

  - name: Disallow empty passwords (Centos)
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords\s'
      line: 'PermitEmptyPasswords no'
      state: present
    notify: Restart sshd

  - name: Disallow password authentication (Centos)
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication\s'
      line: 'PasswordAuthentication no'
      state: present
    notify: Restart sshd

  when: ansible_os_family == "RedHat"

- block:

  - name: update the system (Debian)
    raw: sudo apt-get update
    register: debianupdate_result
    changed_when: False
    until: debianupdate_result is success
    retries: 5
    ignore_errors: yes

  - name: upgrade the system (Debian)
    apt:
      name: "*"
      state: latest
      force_apt_get: True

  - name: Install Packages (Debian)
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ initial_packages_debian }}"
    ignore_errors: yes

  - name: Disallow root SSH access (Debian)
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\s'
      line: 'PermitRootLogin no'
      state: present
    notify: Restart ssh

  - name: Disallow empty passwords (Debian)
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords\s'
      line: 'PermitEmptyPasswords no'
      state: present
    notify: Restart ssh

  - name: Disallow password authentication (Debian)
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication\s'
      line: 'PasswordAuthentication no'
      state: present
    notify: Restart ssh

  when: ansible_os_family == "Debian"
