---
base_path           : home/devuser
development_path    : projects

#Flask
flask_image         : 'uav2608/flask:0.0.2'
#flask_project_name  : flask-app1
flask_project_path  : "{{flask_project_name}}"
flask_template_title: flask-app

#React
react_image         : 'uav2608/react:0.0.2'
#react_project_name  : todo-app1
react_project_path  : "{{react_project_name}}"
react_template_title: todo-app
